"""
seed_destinations.py
────────────────────────────────────────────────────────
Full destination seed — 60+ destinations matching the
mock LLM hints, mapped exactly to the Destination model.

Place in backend/ root (same level as app/).

Usage:
    python seed_destinations.py          # insert + ingest
    python seed_destinations.py --clear  # wipe and re-seed
"""

import json
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from app.database.session import SessionLocal
from app.database.models import Destination
from app.services import vector_store

DESTINATIONS = [
    # ── Asia ──────────────────────────────────────────────────
    {"name":"Bali","country":"Indonesia","continent":"Asia","description":"A magical island of temple rituals, terraced rice fields, surf beaches, and Ubud wellness culture. Bali blends deep spiritual tradition with lush tropical beauty.","climate_type":"tropical","destination_type":"beach","budget_level":"budget","best_months":"April, May, June, July, August, September","avg_temp_c":28.0,"tags":json.dumps(["beach","temples","surfing","wellness","culture","rice terraces"]),"image_url":"https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80","latitude":-8.340539,"longitude":115.091949},
    {"name":"Kyoto","country":"Japan","continent":"Asia","description":"Ancient capital of Japan with quiet temples, bamboo groves, traditional tea houses, zen gardens, and the lantern-lit lanes of Gion district.","climate_type":"temperate","destination_type":"cultural","budget_level":"moderate","best_months":"March, April, May, October, November","avg_temp_c":15.5,"tags":json.dumps(["temples","culture","history","gardens","food","cherry blossoms"]),"image_url":"https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80","latitude":35.011636,"longitude":135.768029},
    {"name":"Tokyo","country":"Japan","continent":"Asia","description":"A city of electric contrasts — neon-lit crossings, silent temples, world-class sushi counters, pop culture districts, and the most precise transit system on earth.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"March, April, May, October, November","avg_temp_c":15.4,"tags":json.dumps(["food","technology","culture","shopping","nightlife","art","anime"]),"image_url":"https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80","latitude":35.689487,"longitude":139.691711},
    {"name":"Chiang Mai","country":"Thailand","continent":"Asia","description":"Northern Thailand's cultural heart — ancient temple circuits, mountain village treks, elephant sanctuaries, vibrant night markets, and world-class northern Thai street food.","climate_type":"tropical","destination_type":"cultural","budget_level":"budget","best_months":"November, December, January, February","avg_temp_c":26.0,"tags":json.dumps(["temples","food","markets","trekking","elephants","culture","night markets"]),"image_url":"https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80","latitude":18.788996,"longitude":98.988631},
    {"name":"Maldives","country":"Maldives","continent":"Asia","description":"Overwater villas above crystalline lagoons, thriving coral reefs, pristine sandbanks, sunset spa rituals, and some of the most serene ocean days on earth.","climate_type":"tropical","destination_type":"beach","budget_level":"luxury","best_months":"November, December, January, February, March, April","avg_temp_c":29.0,"tags":json.dumps(["luxury","snorkeling","romance","beach","diving","overwater villas","relaxation"]),"image_url":"https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80","latitude":3.202778,"longitude":73.220680},
    {"name":"Jaipur","country":"India","continent":"Asia","description":"The Pink City of Rajasthan — hilltop amber forts, ornate palace rooms, vibrant block-printing bazaars, camel rides, and extraordinary Rajasthani cuisine.","climate_type":"arid","destination_type":"cultural","budget_level":"budget","best_months":"October, November, December, January, February, March","avg_temp_c":23.0,"tags":json.dumps(["forts","culture","history","shopping","food","photography","palaces"]),"image_url":"https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80","latitude":26.912434,"longitude":75.787271},
    {"name":"Goa","country":"India","continent":"Asia","description":"Portuguese colonial lanes, palm-fringed beach shacks, aromatic spice farms, river island villages, and relaxed coastal nights with fresh seafood and cold beer.","climate_type":"tropical","destination_type":"beach","budget_level":"budget","best_months":"November, December, January, February","avg_temp_c":27.0,"tags":json.dumps(["beach","food","history","nightlife","water sports","relaxation"]),"image_url":"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80","latitude":15.299326,"longitude":74.123996},
    {"name":"Varanasi","country":"India","continent":"Asia","description":"One of the world's oldest cities — Ganges river rituals at dawn, narrow old-city alleys, sunrise boat rides, silk markets, and a profound spiritual atmosphere.","climate_type":"temperate","destination_type":"cultural","budget_level":"budget","best_months":"October, November, December, January, February, March","avg_temp_c":22.0,"tags":json.dumps(["spirituality","history","culture","rivers","photography","food","ghats"]),"image_url":"https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80","latitude":25.317645,"longitude":83.010822},
    {"name":"Ladakh","country":"India","continent":"Asia","description":"High-altitude desert passes, ancient cliff-side monasteries, lunar valleys, impossibly blue Pangong Lake, and acclimatized adventure at the roof of the world.","climate_type":"cold","destination_type":"adventure","budget_level":"moderate","best_months":"June, July, August, September","avg_temp_c":5.0,"tags":json.dumps(["mountains","monasteries","adventure","photography","trekking","culture","lakes"]),"image_url":"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80","latitude":34.152588,"longitude":77.577049},
    {"name":"Hanoi","country":"Vietnam","continent":"Asia","description":"Old Quarter lanes full of street food vendors, lakeside morning rituals, craft villages, colonial-era architecture, and the best coffee culture in Southeast Asia.","climate_type":"temperate","destination_type":"cultural","budget_level":"budget","best_months":"October, November, December, January, February, March, April","avg_temp_c":23.0,"tags":json.dumps(["food","culture","history","coffee","markets","lakes","photography"]),"image_url":"https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80","latitude":21.027764,"longitude":105.834160},
    {"name":"Hoi An","country":"Vietnam","continent":"Asia","description":"A UNESCO-listed ancient town of lantern-lit streets, tailor workshops, river island cycle routes, pristine beach breaks, and central Vietnamese cooking at its finest.","climate_type":"tropical","destination_type":"cultural","budget_level":"budget","best_months":"February, March, April","avg_temp_c":25.0,"tags":json.dumps(["lanterns","food","history","beach","cycling","tailors","culture"]),"image_url":"https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=800&q=80","latitude":15.879862,"longitude":108.335106},
    {"name":"Seoul","country":"South Korea","continent":"Asia","description":"Ancient palaces beside K-pop studios, traditional hanok villages next to design districts, mountain viewpoints above neon markets, and late-night street food culture.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"April, May, June, September, October, November","avg_temp_c":12.5,"tags":json.dumps(["food","culture","k-pop","history","shopping","nightlife","technology"]),"image_url":"https://images.unsplash.com/photo-1538669715315-155098f0fb1d?w=800&q=80","latitude":37.566535,"longitude":126.977969},
    {"name":"Hong Kong","country":"China","continent":"Asia","description":"Iconic harbour ferry rides, legendary dim sum, dragon-back ridge hikes, neon-soaked night markets, and one of the world's most dramatic urban skylines.","climate_type":"tropical","destination_type":"city","budget_level":"moderate","best_months":"October, November, December","avg_temp_c":23.0,"tags":json.dumps(["food","skyline","hiking","shopping","culture","dim sum","nightlife"]),"image_url":"https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=800&q=80","latitude":22.319304,"longitude":114.169361},
    {"name":"Singapore","country":"Singapore","continent":"Asia","description":"World-class hawker centre food, futuristic garden domes, multicultural heritage quarters, river walk architecture, and an efficient city-state that rewards curious wandering.","climate_type":"tropical","destination_type":"city","budget_level":"luxury","best_months":"February, March, April","avg_temp_c":27.5,"tags":json.dumps(["food","gardens","culture","architecture","shopping","clean","multicultural"]),"image_url":"https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80","latitude":1.352083,"longitude":103.819836},
    {"name":"Dubai","country":"UAE","continent":"Asia","description":"Futuristic skylines rising from desert dunes, traditional gold and spice souks, luxury beach clubs, world-record attractions, and remarkably ambitious dining.","climate_type":"arid","destination_type":"city","budget_level":"luxury","best_months":"November, December, January, February, March","avg_temp_c":28.0,"tags":json.dumps(["luxury","shopping","architecture","desert","beach","food","modern"]),"image_url":"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80","latitude":25.204849,"longitude":55.270783},
    {"name":"Istanbul","country":"Turkey","continent":"Asia","description":"Where Europe meets Asia — Byzantine mosques, Bosphorus ferry crossings, labyrinthine bazaars, Ottoman hammams, and a layered history spanning multiple empires.","climate_type":"temperate","destination_type":"cultural","budget_level":"moderate","best_months":"April, May, June, September, October, November","avg_temp_c":14.0,"tags":json.dumps(["history","food","culture","mosques","markets","bosphorus","architecture"]),"image_url":"https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80","latitude":41.008240,"longitude":28.978359},
    {"name":"Sri Lanka","country":"Sri Lanka","continent":"Asia","description":"Mist-covered tea plantations, ancient rock fortresses, world-class surf beaches, leopard safari drives, and fragrant rice-and-curry meals that change by region.","climate_type":"tropical","destination_type":"adventure","budget_level":"budget","best_months":"December, January, February, March","avg_temp_c":27.0,"tags":json.dumps(["tea","history","beach","wildlife","surfing","food","ruins"]),"image_url":"https://images.unsplash.com/photo-1580181127137-0d4d5d58d1e5?w=800&q=80","latitude":7.873054,"longitude":80.771797},
    {"name":"Nepal","country":"Nepal","continent":"Asia","description":"Himalayan mountain viewpoints, ancient Buddhist stupas, classic trekking routes, steaming momo dumplings, and mountain-flight mornings above the highest peaks on earth.","climate_type":"cold","destination_type":"adventure","budget_level":"budget","best_months":"October, November, March, April","avg_temp_c":10.0,"tags":json.dumps(["trekking","mountains","culture","buddhism","himalayas","food","wildlife"]),"image_url":"https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80","latitude":28.394857,"longitude":84.124008},
    {"name":"Uzbekistan","country":"Uzbekistan","continent":"Asia","description":"The great Silk Road cities of Samarkand and Bukhara — turquoise-tiled madrasas, caravanserai ruins, high-speed train journeys, and extraordinary plov feasts.","climate_type":"arid","destination_type":"cultural","budget_level":"budget","best_months":"April, May, September, October","avg_temp_c":16.0,"tags":json.dumps(["silk road","history","architecture","culture","food","mosques","ancient"]),"image_url":"https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?w=800&q=80","latitude":41.377491,"longitude":64.585262},
    {"name":"Petra","country":"Jordan","continent":"Asia","description":"The rose-red Nabataean city carved into desert canyons — the Siq gorge, the Treasury facade, the Monastery, Bedouin tea camps, and stargazing over Wadi Rum.","climate_type":"arid","destination_type":"cultural","budget_level":"moderate","best_months":"March, April, May, September, October, November","avg_temp_c":18.0,"tags":json.dumps(["history","archaeology","desert","hiking","culture","ancient","photography"]),"image_url":"https://images.unsplash.com/photo-1579606032821-4d6b4c0439c4?w=800&q=80","latitude":30.328611,"longitude":35.444444},

    # ── Europe ─────────────────────────────────────────────────
    {"name":"Santorini","country":"Greece","continent":"Europe","description":"Iconic whitewashed villages perched on volcanic caldera cliffs, black sand beaches, world-class Aegean sunsets, exceptional local wine, and romantic overwater dining.","climate_type":"mediterranean","destination_type":"beach","budget_level":"luxury","best_months":"May, June, September, October","avg_temp_c":20.0,"tags":json.dumps(["romance","views","beach","wine","island","sunsets","architecture"]),"image_url":"https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80","latitude":36.393155,"longitude":25.461509},
    {"name":"Amalfi Coast","country":"Italy","continent":"Europe","description":"Dramatic cliff villages draped in lemon groves above the Tyrrhenian Sea, hidden boat coves, cliff-side hiking paths, and legendary coastal seafood lunches.","climate_type":"mediterranean","destination_type":"beach","budget_level":"luxury","best_months":"May, June, September, October","avg_temp_c":20.5,"tags":json.dumps(["coast","villages","food","hiking","boats","lemons","views"]),"image_url":"https://images.unsplash.com/photo-1533606688076-b6683a5f5f62?w=800&q=80","latitude":40.633333,"longitude":14.602778},
    {"name":"Tuscany","country":"Italy","continent":"Europe","description":"Rolling vineyard hills, Renaissance hilltop towns, cypress-lined country roads, slow winery lunches, and the golden light of late-afternoon Val d'Orcia.","climate_type":"mediterranean","destination_type":"countryside","budget_level":"moderate","best_months":"April, May, June, September, October","avg_temp_c":16.0,"tags":json.dumps(["wine","food","history","countryside","art","cycling","villages"]),"image_url":"https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&q=80","latitude":43.771033,"longitude":11.248000},
    {"name":"Rome","country":"Italy","continent":"Europe","description":"Ancient ruins beside baroque piazzas, world-class Vatican art, neighbourhood trattorias, cobblestone alleys, and the inexhaustible depth of the Eternal City.","climate_type":"mediterranean","destination_type":"cultural","budget_level":"moderate","best_months":"April, May, June, September, October","avg_temp_c":15.5,"tags":json.dumps(["history","food","art","architecture","culture","ruins","vatican"]),"image_url":"https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80","latitude":41.902782,"longitude":12.496366},
    {"name":"Barcelona","country":"Spain","continent":"Europe","description":"Gaudí's impossible architecture, Gothic quarter lanes, beach afternoons, legendary tapas routes, buzzing Boqueria market, and an electric nightlife culture.","climate_type":"mediterranean","destination_type":"city","budget_level":"moderate","best_months":"May, June, September, October","avg_temp_c":18.5,"tags":json.dumps(["architecture","food","beach","nightlife","art","culture","markets"]),"image_url":"https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80","latitude":41.385064,"longitude":2.173403},
    {"name":"Lisbon","country":"Portugal","continent":"Europe","description":"Sun-bleached hillside neighbourhoods, ornate azulejo tile facades, vintage tram rides, sardine restaurants, miradouros viewpoints, and melancholy fado evenings.","climate_type":"mediterranean","destination_type":"city","budget_level":"budget","best_months":"April, May, June, September, October","avg_temp_c":17.5,"tags":json.dumps(["trams","food","history","viewpoints","music","beaches","culture"]),"image_url":"https://images.unsplash.com/photo-1588598198321-9735fd6cf60b?w=800&q=80","latitude":38.722252,"longitude":-9.139337},
    {"name":"Paris","country":"France","continent":"Europe","description":"Museum mornings, market streets, Seine riverbank walks, neighbourhood bistros, world-class patisseries, and the endlessly photogenic details of the most visited city on earth.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"April, May, June, September, October","avg_temp_c":12.5,"tags":json.dumps(["art","food","romance","fashion","museums","architecture","culture"]),"image_url":"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80","latitude":48.856613,"longitude":2.352222},
    {"name":"London","country":"United Kingdom","continent":"Europe","description":"Royal parks, world-class museums, Borough Market, the South Bank, live West End theatre, and endlessly diverse neighbourhood food cultures.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"May, June, July, August, September, December","avg_temp_c":12.0,"tags":json.dumps(["culture","museums","food","history","theatre","parks","shopping"]),"image_url":"https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80","latitude":51.507351,"longitude":-0.127758},
    {"name":"Amsterdam","country":"Netherlands","continent":"Europe","description":"Golden Age canal houses, world-class cycling routes, Rijksmuseum masterpieces, Saturday markets, cosy brown cafes, and design shops in the Jordaan neighbourhood.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"April, May, June, September","avg_temp_c":10.0,"tags":json.dumps(["canals","cycling","art","museums","culture","markets","history"]),"image_url":"https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80","latitude":52.370216,"longitude":4.895168},
    {"name":"Prague","country":"Czech Republic","continent":"Europe","description":"A fairy-tale medieval city — castle hilltop views, Gothic stone bridges, world-class beer halls, art nouveau cafes, and baroque lanes that feel untouched by time.","climate_type":"temperate","destination_type":"cultural","budget_level":"budget","best_months":"April, May, June, September, October","avg_temp_c":10.0,"tags":json.dumps(["history","architecture","beer","culture","food","castles","photography"]),"image_url":"https://images.unsplash.com/photo-1541849546-216549ae216d?w=800&q=80","latitude":50.075539,"longitude":14.437800},
    {"name":"Vienna","country":"Austria","continent":"Europe","description":"Imperial palaces, grand concert halls, legendary Viennese coffee houses, Naschmarkt lunch stops, and an elegant refinement that permeates every cobbled street.","climate_type":"temperate","destination_type":"cultural","budget_level":"moderate","best_months":"April, May, June, September, October, December","avg_temp_c":11.0,"tags":json.dumps(["music","art","food","history","architecture","coffee","palaces"]),"image_url":"https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=800&q=80","latitude":48.208174,"longitude":16.373819},
    {"name":"Budapest","country":"Hungary","continent":"Europe","description":"Grand thermal baths, ruin bar culture, Danube bridges at night, ornate market halls, art nouveau details, and one of Europe's most underrated food scenes.","climate_type":"temperate","destination_type":"city","budget_level":"budget","best_months":"April, May, June, September, October","avg_temp_c":11.5,"tags":json.dumps(["baths","nightlife","history","food","architecture","culture","river"]),"image_url":"https://images.unsplash.com/photo-1565426873118-a17ed65d74b9?w=800&q=80","latitude":47.497912,"longitude":19.040235},
    {"name":"Berlin","country":"Germany","continent":"Europe","description":"Cold War history, world-class galleries, cutting-edge techno scene, street food from every continent, green neighbourhood parks, and an irrepressible creative energy.","climate_type":"temperate","destination_type":"city","budget_level":"budget","best_months":"May, June, July, August, September","avg_temp_c":10.0,"tags":json.dumps(["history","nightlife","art","food","culture","music","architecture"]),"image_url":"https://images.unsplash.com/photo-1560969184-10fe8719e047?w=800&q=80","latitude":52.520008,"longitude":13.404954},
    {"name":"Copenhagen","country":"Denmark","continent":"Europe","description":"Colourful harbour canals, world-leading design culture, effortless cycling lanes, New Nordic cuisine, Tivoli Gardens, and a quality of life that shows in every detail.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"May, June, July, August, September","avg_temp_c":9.0,"tags":json.dumps(["design","food","cycling","culture","architecture","markets","canals"]),"image_url":"https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=800&q=80","latitude":55.676098,"longitude":12.568337},
    {"name":"Stockholm","country":"Sweden","continent":"Europe","description":"A city spread across 14 islands — Gamla Stan old-town lanes, Viking museums, archipelago ferry hops, fika coffee breaks, and Scandinavian design at every turn.","climate_type":"cold","destination_type":"city","budget_level":"luxury","best_months":"June, July, August, December","avg_temp_c":8.0,"tags":json.dumps(["design","history","islands","culture","food","museums","nature"]),"image_url":"https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=800&q=80","latitude":59.334591,"longitude":18.063240},
    {"name":"Oslo","country":"Norway","continent":"Europe","description":"Fjord-side saunas, Nordmarka forest metro rides, Vigeland sculpture parks, world-class modern museums, and a Nordic waterfront with exceptional seafood restaurants.","climate_type":"cold","destination_type":"city","budget_level":"luxury","best_months":"May, June, July, August, September","avg_temp_c":7.0,"tags":json.dumps(["fjords","nature","museums","food","culture","hiking","design"]),"image_url":"https://images.unsplash.com/photo-1531761535209-180857e963b9?w=800&q=80","latitude":59.913868,"longitude":10.752245},
    {"name":"Reykjavik","country":"Iceland","continent":"Europe","description":"Geothermal pools, volcanic coastlines, thundering waterfalls, northern lights in winter, and the Golden Circle — all within reach of a compact Nordic capital.","climate_type":"cold","destination_type":"adventure","budget_level":"luxury","best_months":"June, July, August, September, October, November","avg_temp_c":4.5,"tags":json.dumps(["northern lights","geothermal","waterfalls","hiking","nature","photography","aurora"]),"image_url":"https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80","latitude":64.126521,"longitude":-21.817439},
    {"name":"Dubrovnik","country":"Croatia","continent":"Europe","description":"A perfectly preserved medieval walled city on the Adriatic, with limestone-cobbled lanes, island ferry hops, sea kayaking, and exceptional coastal seafood terraces.","climate_type":"mediterranean","destination_type":"cultural","budget_level":"moderate","best_months":"May, June, September, October","avg_temp_c":18.0,"tags":json.dumps(["history","beach","islands","food","architecture","kayaking","walls"]),"image_url":"https://images.unsplash.com/photo-1555990538-1ebbb6a39dbc?w=800&q=80","latitude":42.650661,"longitude":18.094424},
    {"name":"Athens","country":"Greece","continent":"Europe","description":"Ancient hilltop ruins above a living modern city — Acropolis viewpoints, neighbourhood tavernas, island ferry connections, and rooftop sunset dining.","climate_type":"mediterranean","destination_type":"cultural","budget_level":"moderate","best_months":"April, May, June, September, October","avg_temp_c":18.5,"tags":json.dumps(["history","ruins","food","culture","islands","art","architecture"]),"image_url":"https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80","latitude":37.983810,"longitude":23.727539},
    {"name":"Edinburgh","country":"Scotland","continent":"Europe","description":"A dramatic volcanic castle rock, literary pub culture, whisky tasting rooms, coastal village day trips, and moody medieval streets that inspired generations of writers.","climate_type":"temperate","destination_type":"cultural","budget_level":"moderate","best_months":"May, June, July, August, September, December","avg_temp_c":9.0,"tags":json.dumps(["history","whisky","culture","castles","literature","food","festivals"]),"image_url":"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80","latitude":55.953252,"longitude":-3.188267},
    {"name":"Dublin","country":"Ireland","continent":"Europe","description":"Literary pub culture, Georgian garden squares, Howth coastal village walks, live trad music sessions, and one of the warmest welcomes of any capital city in Europe.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"May, June, July, August, September","avg_temp_c":10.0,"tags":json.dumps(["pubs","history","music","food","culture","literature","coast"]),"image_url":"https://images.unsplash.com/photo-1564959130747-897fb406b9af?w=800&q=80","latitude":53.349805,"longitude":-6.260310},
    {"name":"Swiss Alps","country":"Switzerland","continent":"Europe","description":"Cog railways to glacier viewpoints, wildflower meadow hikes, charming chalet villages, world-class ski runs, and fondue evenings in candlelit mountain restaurants.","climate_type":"cold","destination_type":"mountain","budget_level":"luxury","best_months":"June, July, August, September, December, January, February","avg_temp_c":5.0,"tags":json.dumps(["skiing","hiking","glaciers","scenery","food","villages","trains"]),"image_url":"https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=800&q=80","latitude":46.818188,"longitude":8.227512},

    # ── Africa ─────────────────────────────────────────────────
    {"name":"Marrakech","country":"Morocco","continent":"Africa","description":"A sensory maze of ancient souks, palace courtyards, rooftop mint teas, traditional hammams, and gateway desert excursions at the edge of the Sahara.","climate_type":"arid","destination_type":"cultural","budget_level":"budget","best_months":"March, April, October, November","avg_temp_c":22.0,"tags":json.dumps(["souks","culture","history","food","desert","architecture","hammam"]),"image_url":"https://images.unsplash.com/photo-1548017787-e2d459e8f29d?w=800&q=80","latitude":31.628674,"longitude":-7.992047},
    {"name":"Morocco Sahara","country":"Morocco","continent":"Africa","description":"Towering Erg Chebbi dunes, camel silhouettes at sunset, Berber desert camps under a sky full of stars, ancient kasbah roads, and extraordinary desert hospitality.","climate_type":"arid","destination_type":"adventure","budget_level":"moderate","best_months":"October, November, December, January, February, March, April","avg_temp_c":20.0,"tags":json.dumps(["desert","dunes","camping","camels","stars","berber","culture"]),"image_url":"https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80","latitude":31.049768,"longitude":-4.012719},
    {"name":"Cape Town","country":"South Africa","continent":"Africa","description":"Table Mountain trails, penguin beaches, Cape Winelands estates, colourful Bo-Kaap streets, and one of the world's most dramatic coastal drives.","climate_type":"mediterranean","destination_type":"city","budget_level":"moderate","best_months":"November, December, January, February, March","avg_temp_c":17.0,"tags":json.dumps(["hiking","wine","beach","wildlife","history","photography","food"]),"image_url":"https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&q=80","latitude":-33.924869,"longitude":18.424055},
    {"name":"Serengeti","country":"Tanzania","continent":"Africa","description":"Endless golden plains hosting the greatest wildlife spectacle on earth — expert-guided game drives, luxury tented camps, acacia sunsets, and the Great Migration.","climate_type":"tropical","destination_type":"adventure","budget_level":"luxury","best_months":"June, July, August, September, October","avg_temp_c":22.5,"tags":json.dumps(["safari","wildlife","migration","photography","nature","lions","camping"]),"image_url":"https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80","latitude":-2.333333,"longitude":34.833333},
    {"name":"Zanzibar","country":"Tanzania","continent":"Africa","description":"Spice farm tours, traditional dhow sailing trips, UNESCO Stone Town Swahili lanes, pristine coral reef beaches, and extraordinary Swahili seafood at sunset.","climate_type":"tropical","destination_type":"beach","budget_level":"moderate","best_months":"June, July, August, September, October, January, February","avg_temp_c":27.0,"tags":json.dumps(["beach","culture","spices","snorkeling","history","food","island"]),"image_url":"https://images.unsplash.com/photo-1586861256632-53f294d41ba0?w=800&q=80","latitude":-6.165917,"longitude":39.202641},
    {"name":"Nairobi","country":"Kenya","continent":"Africa","description":"Urban wildlife viewing inside a national park, specialty coffee farms, vibrant craft markets, rich natural history, and a gateway hub for East African safari adventures.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"June, July, August, September, October, January, February","avg_temp_c":19.0,"tags":json.dumps(["wildlife","safari","culture","food","coffee","markets","nature"]),"image_url":"https://images.unsplash.com/photo-1611348586804-61bf6c080437?w=800&q=80","latitude":-1.292066,"longitude":36.821946},
    {"name":"Cairo","country":"Egypt","continent":"Africa","description":"The last surviving wonder of the ancient world, Nile river views, medieval Islamic lanes, the spectacular Grand Egyptian Museum, and deep pharaonic history.","climate_type":"arid","destination_type":"cultural","budget_level":"budget","best_months":"October, November, December, January, February, March, April","avg_temp_c":22.0,"tags":json.dumps(["pyramids","history","culture","museums","nile","ancient","food"]),"image_url":"https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=800&q=80","latitude":30.044420,"longitude":31.235712},

    # ── South America ──────────────────────────────────────────
    {"name":"Patagonia","country":"Argentina / Chile","continent":"South America","description":"One of the world's last great wildernesses — glacier trails, iconic granite towers, wind-swept steppe, turquoise lakes, and remote mountain lodges.","climate_type":"cold","destination_type":"adventure","budget_level":"moderate","best_months":"November, December, January, February, March","avg_temp_c":8.0,"tags":json.dumps(["trekking","glaciers","wildlife","mountains","nature","remote"]),"image_url":"https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80","latitude":-51.623541,"longitude":-72.703827},
    {"name":"Machu Picchu","country":"Peru","continent":"South America","description":"Inca citadel roads, Sacred Valley villages, cloud forest railway journeys, acclimatized high-altitude ruins, and the magical atmosphere of a lost mountain city.","climate_type":"temperate","destination_type":"cultural","budget_level":"moderate","best_months":"May, June, July, August, September","avg_temp_c":13.0,"tags":json.dumps(["history","ruins","hiking","culture","mountains","photography","inca"]),"image_url":"https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80","latitude":-13.163141,"longitude":-72.545872},
    {"name":"Rio de Janeiro","country":"Brazil","continent":"South America","description":"Beach rhythms, rainforest viewpoints, samba nights, dramatic granite peaks, legendary Carnival energy, and the warmth of carioca culture at every turn.","climate_type":"tropical","destination_type":"city","budget_level":"moderate","best_months":"May, June, July, August, September, October","avg_temp_c":24.0,"tags":json.dumps(["beach","carnival","nightlife","nature","food","culture","mountains"]),"image_url":"https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80","latitude":-22.906847,"longitude":-43.172897},
    {"name":"Buenos Aires","country":"Argentina","continent":"South America","description":"Milonga tango halls, grand European-style avenues, world-class steak dinners, independent bookshops, and a neighbourhood cafe culture that runs until midnight.","climate_type":"temperate","destination_type":"city","budget_level":"budget","best_months":"March, April, May, September, October, November","avg_temp_c":18.0,"tags":json.dumps(["tango","food","culture","nightlife","art","history","steak"]),"image_url":"https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=800&q=80","latitude":-34.603684,"longitude":-58.381559},
    {"name":"Galapagos","country":"Ecuador","continent":"South America","description":"Wildlife landings with fearless iguanas and sea lions, lava trail hikes, snorkeling coves with sea turtles, conservation research stations, and boat-led island days.","climate_type":"tropical","destination_type":"adventure","budget_level":"luxury","best_months":"December, January, February, March, June, July, August","avg_temp_c":24.0,"tags":json.dumps(["wildlife","snorkeling","nature","diving","conservation","photography","islands"]),"image_url":"https://images.unsplash.com/photo-1548681528-6a5c45b66063?w=800&q=80","latitude":-0.966667,"longitude":-90.966667},
    {"name":"Cartagena","country":"Colombia","continent":"South America","description":"Caribbean colonial walled city with colourful balconies, Getsemaní street art, island boat trips, salsa nights, and extraordinary fresh coastal seafood.","climate_type":"tropical","destination_type":"cultural","budget_level":"moderate","best_months":"December, January, February, March, April","avg_temp_c":28.0,"tags":json.dumps(["history","beach","culture","food","nightlife","architecture","islands"]),"image_url":"https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800&q=80","latitude":10.391049,"longitude":-75.479426},

    # ── North America ──────────────────────────────────────────
    {"name":"Mexico City","country":"Mexico","continent":"North America","description":"Diego Rivera murals, market taco culture, leafy Roma Norte barrios, Teotihuacan pyramids, Xochimilco canals, and a contemporary gallery scene of genuine depth.","climate_type":"temperate","destination_type":"cultural","budget_level":"budget","best_months":"March, April, May, October, November","avg_temp_c":18.0,"tags":json.dumps(["food","art","history","culture","markets","nightlife","architecture"]),"image_url":"https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800&q=80","latitude":19.432608,"longitude":-99.133209},
    {"name":"New York City","country":"USA","continent":"North America","description":"Iconic skyline walks, borough food cultures, the Metropolitan Museum, Broadway shows, Central Park mornings, and a city that delivers something new every single day.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"April, May, June, September, October, November","avg_temp_c":13.0,"tags":json.dumps(["culture","food","art","shopping","nightlife","architecture","museums"]),"image_url":"https://images.unsplash.com/photo-1522083165195-3424ed129620?w=800&q=80","latitude":40.712776,"longitude":-74.005974},
    {"name":"San Francisco","country":"USA","continent":"North America","description":"Bay Area ferry rides, Mission District murals, the Ferry Building food market, Alcatraz history, Muir Woods redwoods, and neighbourhood food culture second to none.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"September, October, November","avg_temp_c":14.0,"tags":json.dumps(["food","culture","technology","nature","art","history","bay"]),"image_url":"https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80","latitude":37.774929,"longitude":-122.419416},
    {"name":"Las Vegas","country":"USA","continent":"North America","description":"Desert spectacle, resort shows, neon history museum, canyon day trips, late-night chef dining, and the surreal energy of a city built entirely on entertainment.","climate_type":"arid","destination_type":"city","budget_level":"moderate","best_months":"March, April, May, September, October, November","avg_temp_c":20.0,"tags":json.dumps(["entertainment","nightlife","food","shows","desert","casinos","day trips"]),"image_url":"https://images.unsplash.com/photo-1581351721010-8cf859cb14a4?w=800&q=80","latitude":36.169941,"longitude":-115.139832},
    {"name":"Vancouver","country":"Canada","continent":"North America","description":"Seawall cycling with mountain backdrops, Granville Island markets, exceptional Asian food, whale watching ferries, Stanley Park old-growth forest, and Pacific Ocean views.","climate_type":"temperate","destination_type":"city","budget_level":"moderate","best_months":"June, July, August, September","avg_temp_c":11.0,"tags":json.dumps(["nature","food","cycling","mountains","culture","seafood","skiing"]),"image_url":"https://images.unsplash.com/photo-1559511260-66a654ae982a?w=800&q=80","latitude":49.282729,"longitude":-123.120738},
    {"name":"Banff","country":"Canada","continent":"North America","description":"Turquoise glacier-fed lakes, alpine meadows, wildlife corridors, world-class ski runs, and cosy mountain lodges deep inside the Canadian Rockies.","climate_type":"cold","destination_type":"mountain","budget_level":"moderate","best_months":"June, July, August, September, December, January, February","avg_temp_c":4.0,"tags":json.dumps(["mountains","lakes","hiking","skiing","wildlife","photography","nature"]),"image_url":"https://images.unsplash.com/photo-1609096458733-95b38583ac4e?w=800&q=80","latitude":51.178363,"longitude":-115.570769},
    {"name":"Grand Canyon","country":"USA","continent":"North America","description":"Rim walks above one billion years of exposed geology, desert sunrise viewpoints, mule train history, Colorado River rapids below, and extraordinary star-filled nights.","climate_type":"arid","destination_type":"adventure","budget_level":"budget","best_months":"March, April, May, September, October, November","avg_temp_c":16.0,"tags":json.dumps(["nature","hiking","photography","geology","adventure","views","camping"]),"image_url":"https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&q=80","latitude":36.106965,"longitude":-112.112997},
    {"name":"Yellowstone","country":"USA","continent":"North America","description":"Geysers erupting on schedule, bison herds blocking roads, Grand Canyon of the Yellowstone, prismatic thermal springs, and extraordinary wildlife in a supervolcano caldera.","climate_type":"cold","destination_type":"adventure","budget_level":"budget","best_months":"May, June, July, August, September","avg_temp_c":8.0,"tags":json.dumps(["nature","wildlife","geysers","photography","hiking","camping","geology"]),"image_url":"https://images.unsplash.com/photo-1533423996375-f914b29c3f91?w=800&q=80","latitude":44.427963,"longitude":-110.588455},

    # ── Oceania ────────────────────────────────────────────────
    {"name":"Sydney","country":"Australia","continent":"Oceania","description":"Iconic harbour icons, Bondi coastal walks, morning surf culture, ferry island hops, Blue Mountains day trips, and a modern Australian food scene of genuine excellence.","climate_type":"temperate","destination_type":"city","budget_level":"luxury","best_months":"September, October, November, March, April, May","avg_temp_c":17.7,"tags":json.dumps(["beach","harbour","food","culture","hiking","surfing","nature"]),"image_url":"https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&q=80","latitude":-33.868820,"longitude":151.209296},
    {"name":"Queenstown","country":"New Zealand","continent":"Oceania","description":"The adventure capital of the world — bungee jumping, jet boats, alpine hikes, stunning lakefront views, world-class wineries, and the gateway to Fiordland.","climate_type":"temperate","destination_type":"adventure","budget_level":"moderate","best_months":"December, January, February, June, July, August","avg_temp_c":10.5,"tags":json.dumps(["adventure","bungee","skiing","hiking","wine","lakes","scenery"]),"image_url":"https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800&q=80","latitude":-45.031162,"longitude":168.662643},
]


def seed(clear_existing: bool = False):
    db = SessionLocal()
    try:
        existing = db.query(Destination).count()

        if existing > 0 and not clear_existing:
            print(f"⚠️  {existing} destinations already in DB.")
            print("   Run with --clear to wipe and re-seed.")
            print("   Skipping insert, running ChromaDB ingest only...\n")
        else:
            if clear_existing and existing > 0:
                print(f"🗑️  Clearing {existing} existing destinations...")
                db.query(Destination).delete()
                db.commit()

            print(f"📦 Inserting {len(DESTINATIONS)} destinations into MariaDB...")
            for d in DESTINATIONS:
                db.add(Destination(**d))
            db.commit()
            print(f"✅ Inserted {len(DESTINATIONS)} destinations.\n")

        print("🔍 Ingesting into ChromaDB vector store...")
        ids = vector_store.ingest_destinations(db)
        count = len(ids)
        print(f"✅ Ingested {count} destinations into ChromaDB.")
        print("\n🎉 All done! Refresh your app to see all destinations.")

    except Exception as e:
        db.rollback()
        print(f"\n❌ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    clear = "--clear" in sys.argv
    seed(clear_existing=clear)